### ISSUE TITLE
Recording stops after a certain time 

### ISSUE THREAD

**Issue by MrKalleOH** [NHLGames/NHLGames#228]
Usally I have had no problem recording games, but since the last week, some games (especially Nashville Fox-TN) has not worked for me. Once I start recording a game it stops after a certain interval (1,6-2,5GB) and displays this error message:

[download][..VAN_vs_STL_Home_SNP.mp4] Written 3.20 GB (4m57s @ 11.1 MB/s)      Exception in thread Thread-HLSStreamWriter:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "D:\NHLGames-v1.3.2.2-complete\streamlink\Streamlink\streamlink\stream\segmented.py", line 167, in run
    self.write(segment, result)
  File "D:\NHLGames-v1.3.2.2-complete\streamlink\Streamlink\streamlink\stream\hls.py", line 135, in write
    self.reader.buffer.write(pkcs7_decode(decrypted_chunk))
  File "D:\NHLGames-v1.3.2.2-complete\streamlink\Streamlink\streamlink\stream\hls.py", line 31, in pkcs7_decode
    raise StreamError("Input is not padded or padding is corrupt, got padding size of {0}".format(val))
streamlink.exceptions.StreamError: Input is not padded or padding is corrupt, got padding size of 242

**To Reproduce**
1. Start NHLGames
2. Select Output in the settings (excellent mode)
3. Pick a game and choose which channel

**Expected behavior**
Normally it records the whole game and the end file is about 6-7GB in size. 

**Console log**
[download][..VAN_vs_STL_Home_SNP.mp4] Written 3.20 GB (4m57s @ 11.1 MB/s)      Exception in thread Thread-HLSStreamWriter:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "D:\NHLGames-v1.3.2.2-complete\streamlink\Streamlink\streamlink\stream\segmented.py", line 167, in run
    self.write(segment, result)
  File "D:\NHLGames-v1.3.2.2-complete\streamlink\Streamlink\streamlink\stream\hls.py", line 135, in write
    self.reader.buffer.write(pkcs7_decode(decrypted_chunk))
  File "D:\NHLGames-v1.3.2.2-complete\streamlink\Streamlink\streamlink\stream\hls.py", line 31, in pkcs7_decode
    raise StreamError("Input is not padded or padding is corrupt, got padding size of {0}".format(val))
streamlink.exceptions.StreamError: Input is not padded or padding is corrupt, got padding size of 242

**Screenshots**
If applicable, add some screenshots to help explain your problem.

**Comment by MrKalleOH** [comment]
[download][..vs_VAN_National_SN1.mp4] Written 2.37 GB (4m57s @ 9.5 MB/s)       Exception in thread Thread-HLSStreamWriter:
Traceback (most recent call last):
  File "threading.py", line 916, in _bootstrap_inner
  File "D:\NHLGames-v1.3.2.2-complete\streamlink\Streamlink\streamlink\stream\segmented.py", line 167, in run
    self.write(segment, result)
  File "D:\NHLGames-v1.3.2.2-complete\streamlink\Streamlink\streamlink\stream\hls.py", line 135, in write
    self.reader.buffer.write(pkcs7_decode(decrypted_chunk))
  File "D:\NHLGames-v1.3.2.2-complete\streamlink\Streamlink\streamlink\stream\hls.py", line 31, in pkcs7_decode
    raise StreamError("Input is not padded or padding is corrupt, got padding size of {0}".format(val))
streamlink.exceptions.StreamError: Input is not padded or padding is corrupt, got padding size of 43

**Comment by d-kar** [comment]
I had similar issue where recording just stops at some point with version that uses mlbproxy. Because of this I had to switch to old 'hosts' version and everything works fine.

**Comment by MrKalleOH** [comment]
>           I had similar issue where recording just stops at some point with version that uses mlbproxy. Because of this I had to switch to old 'hosts' version and everything works fine.

Thank you for your input on the issue. As it seems, the problem is indeed correlated to mlbproxy and after I downloaded the latest version without mlbroxy included (1,3 complete)- it all worked fine! 

Thanks again, and what a wonderful start of the new year.

**Comment by jwallet** [comment]
the latest version v.1.3.2.4 should fix it, related to streamlink not able to get the proper segment, streamlink team recommanded to increase attempts and timeout as well

**Comment by jwallet** [comment]
might be related to #229

**Comment by MrKalleOH** [comment]
> 
> 
> the latest version v.1.3.2.4 should fix it, related to streamlink not able to get the proper segment, streamlink team recommanded to increase attempts and timeout as well

Nope, I have tried the latest v.1.3.2.5 and the problem still persists upon recording a game: 

> [download][..PHI_vs_VAN_Away_SNP.mp4] Written 3.00 GB (4m57s @ 10.1 MB/s)      Exception in thread Thread-HLSStreamWriter:
> Traceback (most recent call last):
>   File "threading.py", line 916, in _bootstrap_inner
>   File "C:\Users\Kalle\Downloads\NHLGames-v1.3.2.5-complete\streamlink\Streamlink\streamlink\stream\segmented.py", line 167, in run
>     self.write(segment, result)
>   File "C:\Users\Kalle\Downloads\NHLGames-v1.3.2.5-complete\streamlink\Streamlink\streamlink\stream\hls.py", line 135, in write
>     self.reader.buffer.write(pkcs7_decode(decrypted_chunk))
>   File "C:\Users\Kalle\Downloads\NHLGames-v1.3.2.5-complete\streamlink\Streamlink\streamlink\stream\hls.py", line 31, in pkcs7_decode
>     raise StreamError("Input is not padded or padding is corrupt, got padding size of {0}".format(val))
> streamlink.exceptions.StreamError: Input is not padded or padding is corrupt, got padding size of 68


 **I will continue to use v.1.3.0 as it works flawlessly at the moment.** 

> 
> 
> might be related to #229

I don't think it's related as I'm not streaming a game on the fly via chromecast. I'm recording a game and it appears the downloading stream crashes when connection bandwidth is too high or unstable. 

Both my examples above state: 

> "raise StreamError("Input is not padded or padding is corrupt, got padding size of {0}".format(val))
> streamlink.exceptions.StreamError: Input is not padded or padding is corrupt," with different padding size values. 

In comparison the problem you refered to being interconnected state this error: 

> "error: error when reading from stream: read timeout, exiting [16:47:28] [console][info] stream ended [16:47:28] [console][info] closing currently open stream... [16:47:28] [end of streamlink for windows with exitcode 1]"

**Comment by jwallet** [comment]
can you try if this still happens with the latest version [1.3.3](https://github.com/NHLGames/NHLGames/releases/latest)

**Comment by MrKalleOH** [comment]
> 
> 
> can you try if this still happens with the latest version [1.3.3](https://github.com/NHLGames/NHLGames/releases/latest)

Wonderful, it works like charm and it's way quicker. One difference though, is that the dialog isn't displaying any data to the user, hence error reporting will be a problem if one occurs in the future.

**Comment by jwallet** [comment]
yes, the streamer that we use, streamlink, no longer display that when using a proxy and we have to be in debug to display it, for what i know, however you may want to try [livestreamer](https://github.com/NHLGames/NHLGames/releases/download/v1.2.0.1/livestreamer.zip) (streamlink version 0) it still displays it.
