### ISSUE TITLE
Livestreamer path incorrect when NHLGames folder is moved

### ISSUE THREAD

**Issue by NHLGames** [NHLGames/NHLGames#37]
Perhaps a flag is needed to decide if a user truly selected a custom path, or if they just moved the folder.  If a user hasn't set a custom path yet, the app should always look for livestreamer in the regular subfolder.

**Comment by jwallet** [comment]
i think this was fixed by checking every launch if the path inside the text box  are valid

**Comment by abumbalough** [comment]
This issue persists in version 1.0.8f. The solution above does not fix the issue.

**Comment by jwallet** [comment]
you sure about it im moving the folder back and forth, from download folder to desktop and to download and everything gets updated

**Comment by jwallet** [comment]
this should be fixed, we now use streamlink standalone, and it extracts itself in appdata
